# Generated by Django 4.1.3 on 2022-11-14 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalNotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='auther',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship', to='personalNotes.auther'),
        ),
    ]
