# Generated by Django 4.1.3 on 2022-11-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalNotes', '0002_alter_note_auther'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auther',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
