# Generated by Django 4.1.3 on 2022-11-14 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalNotes', '0003_alter_auther_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auther',
            options={},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={},
        ),
    ]
