# Generated by Django 4.1.3 on 2022-11-14 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalNotes', '0004_alter_auther_options_alter_note_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auther',
            options={'verbose_name': 'Auther', 'verbose_name_plural': 'Authers'},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
    ]
