# Generated by Django 4.1.3 on 2022-11-14 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalNotes', '0007_alter_auther_slug_alter_note_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auther',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='note',
            name='slug',
        ),
    ]
